# Generated by Django 6.1.1 on 2026-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunks_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='index_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
